/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterUserRequest {
  password: string;
  role: 'BUYER' | 'SELLER';
  username: string;
}
